services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - LDAP_SERVER=ldap
      - LDAP_PORT=389
      - LDAP_BASE_DN=dc=mobilis,dc=dz
      - LDAP_USER_DN=ou=employees,dc=mobilis,dc=dz
      - LDAP_BIND_DN=cn=admin,dc=mobilis,dc=dz
      - LDAP_BIND_PASSWORD=admin_password
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_EXPIRATION=3600
    depends_on:
      - ldap

  ldap:
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=Mobilis Algerie
      - LDAP_DOMAIN=mobilis.dz
      - LDAP_ADMIN_PASSWORD=admin_password
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - "8080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_config: