---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-auth-secrets
  namespace: mobilis-knowledge
type: Opaque
data:
  ldap-bind-password: YWRtaW5fcGFzc3dvcmQ=  # Base64 de 'admin_password'
  jwt-secret: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # À changer en production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-auth-config
  namespace: mobilis-knowledge
data:
  LDAP_SERVER: "ldap.mobilis.dz"
  LDAP_PORT: "389"
  LDAP_BASE_DN: "dc=mobilis,dc=dz"
  LDAP_USER_DN: "ou=employees,dc=mobilis,dc=dz"
  LDAP_BIND_DN: "cn=admin,dc=mobilis,dc=dz"
  JWT_EXPIRATION: "3600"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: mobilis-knowledge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: registry.mobilis.dz/knowledge-base/auth-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: LDAP_SERVER
          valueFrom:
            configMapKeyRef:
              name: ldap-auth-config
              key: LDAP_SERVER
        - name: LDAP_PORT
          valueFrom:
            configMapKeyRef:
              name: ldap-auth-config
              key: LDAP_PORT
        - name: LDAP_BASE_DN
          valueFrom:
            configMapKeyRef:
              name: ldap-auth-config
              key: LDAP_BASE_DN
        - name: LDAP_USER_DN
          valueFrom:
            configMapKeyRef:
              name: ldap-auth-config
              key: LDAP_USER_DN
        - name: LDAP_BIND_DN
          valueFrom:
            configMapKeyRef:
              name: ldap-auth-config
              key: LDAP_BIND_DN
        - name: LDAP_BIND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-auth-secrets
              key: ldap-bind-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ldap-auth-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: ldap-auth-config
              key: JWT_EXPIRATION
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/auth/verify
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/auth/verify
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: mobilis-knowledge
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-service-ingress
  namespace: mobilis-knowledge
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: auth.knowledge.mobilis.dz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
  tls:
  - hosts:
    - auth.knowledge.mobilis.dz
    secretName: mobilis-tls-secret